path:
  model_path: model/
  train_path: ../data/train_dataset/
  test_path: ../data/test_dataset/
  output_path: output/

model:
  #model_name: klue/bert-base
  #model_name: timpal0l/mdeberta-v3-base-squad2
  model_name: FacebookAI/roberta-large
