path:
  model_path: ../models/
  train_path: ../data/train_dataset/
  test_path: ../data/test_dataset/
  output_path: ../output/

model:
  #model_name: uomnf97/klue-roberta-finetuned-korquad-v2
  #model_name: klue/bert-base
  model_name: yjgwak/klue-bert-base-finetuned-squad-kor-v1
  #model_name: klue/roberta-large
  #model_name: timpal0l/mdeberta-v3-base-squad2
  #model_name: monologg/koelectra-base-v3-finetuned-korquad

hyperparameters:
  save_steps : 1500
  metric_for_best_model : eval_f1

retrieval:
  name : bm25
  #name : tfidf

augmentation:
  active : ["synonym_replacement", "random_insertion", "random_deletion", "random_swap"]
  inactive : []